spring:
  application:
    name: msclientes
  datasource:
    url: jdbc:h2:mem:clientes
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://ms-eureka-user:123456@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'